### ISSUE TITLE
Can you add double - click and right - click events

### ISSUE THREAD

**Issue by blksky** [jasonChen1982/three.interaction.js#12]
Your library is very useful to me, but there are still some problems:
1, Hope to be able to increase double-click events and right-click events;
2. When adding an event to the Scene, the event should be triggered even if the object is not hit, which is helpful for some logical processing of the program;

**Comment by jasonChen1982** [comment]
I can't understand point 2, can you give more information about it

**Comment by blksky** [comment]
point 2  is not a problem，i bind event like this, and the problem solved: 
this.interaction = new Interaction(this.renderer, this.scene, this.camera);
this.interaction.addEventListener(EventTypes.mousedown, this.handleMousedown.bind(this));
