### ISSUE TITLE
On Click error ("event is not defined") - Firefox Quantum 57.0.3

### ISSUE THREAD

**Issue by Laver2k** [jasonChen1982/three.interaction.js#3]
Hi! 
I've come across an error where click events don't work in the latest version of Firefox.  Seems to work in other browsers though.

You can replicate it by:
Using Firefox Quantum
Go to https://jasonchen1982.github.io/three.interaction.js/examples/interaction/
Check the console as you try the 'click'.  It doesn't register and an error appears in the console.

**Comment by benjaminnaesen** [comment]
Same issue.

**Comment by jasonChen1982** [comment]
thanks~~ i got it, i will fix it right now

**Comment by jasonChen1982** [comment]
see [this commit](https://github.com/jasonChen1982/three.interaction.js/commit/30b955402b6258418b3484a3fda08d536f72112f#diff-eed3b069005ed70151cc64da1742f449)

**Comment by jasonChen1982** [comment]
it publish in [v0.0.8](https://www.npmjs.com/package/three.interaction)
