### ISSUE TITLE
事件触发

### ISSUE THREAD

**Issue by lc8882972** [jasonChen1982/three.interaction.js#6]
当2个物体重叠时，2个物体的onclick事件都会触发，如何只触发离相机最近的物体的事件

**Comment by jasonChen1982** [comment]
谢谢你的反馈，是应该优先触发离摄像机近的物体，问题已经修复在 v0.2.0 。并且修改了 interactionEvent.intersects 的含义，可以通过该属性访问到所有碰撞到的物体，排序以相对照相机的距离

**Comment by lc8882972** [comment]
更新完之后所有的事件都触发不了

**Comment by jasonChen1982** [comment]
my bad... 方法参数传错了

**Comment by lc8882972** [comment]
射线发送应该是` this.raycaster.intersectObjects( scene.children, true)`
        var cube = new THREE.Mesh(
          new THREE.BoxGeometry(3, 3, 3),
          new THREE.MeshPhongMaterial({ color: 0xffffff })
        );
        cube.cursor = 'pointer';
        cube.position.y = -5;
        cube.position.z = -10;
        cube.name = 'box';
        group.add(cube);
        scene.add(group);`
`
上面的代码无法触发事件

**Comment by jasonChen1982** [comment]
改过了还是不行吗？v0.2.1 改了这个传参数的问题，本来应该是第三个参数的
